version: '3'
services:
  tester:
    #user: "${USERID}:${GROUPID}"
    build: build/nvm
    image: rcx-nodejs-build-nvm-20:latest
    volumes:
        - /etc/passwd:/etc/passwd:ro
        - /etc/group:/etc/group:ro
        - "${WORKSPACE}:${WORKSPACE}"
        - "${JENKINS_HOME}:${JENKINS_HOME}"
    environment:
        BASH_ENV: "/root/.profile"
networks:
  default:
    external:
      name: rcx_sbi
